# Uygulama Adı ve Port
spring.application.name=core-service
server.port=8080

# Veritabanı Bağlantı Ayarları
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aynisindan_core}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ve Hibernate Ayarları (Otomatik tablo oluşturma)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# AWS S3 Configuration
aws.s3.bucket-name=${AWS_S3_BUCKET:aynisindan-sketches}
aws.region=${AWS_REGION:eu-central-1}
aws.access-key=${AWS_ACCESS_KEY:default-access-key}
aws.secret-key=${AWS_SECRET_KEY:default-secret-key}