name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main  # veya hangi branch'i canlıya çıkarmak istiyorsan (develop/main)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Frontend to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: aynisindan-frontend
          IMAGE_TAG: latest
        run: |
          docker build --platform linux/amd64 \
            --build-arg NEXT_PUBLIC_API_URL="http://18.192.48.116:8080/api/v1" \
            --build-arg NEXT_PUBLIC_CATALOG_API_URL="http://18.192.48.116:8081/api/v1" \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./apps/web
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Copy Files to EC2 Server
        uses: appleboy/scp-action@master
        with:
          host: 18.192.48.116
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml,infrastructure/**"
          target: "/home/ec2-user/app"

      - name: Remote SSH Command to Redeploy
        uses: appleboy/ssh-action@master
        with:
          host: 18.192.48.116
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/app
            mv docker-compose.prod.yml docker-compose.yml
            aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
            docker compose pull frontend
            docker compose up -d
            docker image prune -f